# This portfolio being modified by Sulaiha Subi

locale                   : "en-US"
title                    : # nothing
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Sulaiha Subi"
description              : "Data Science Portfolio"
url                      : https://sulaihasubi.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/Sulaiha-Subi.png"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Sulaiha Subi"
  avatar : "/assets/images/dp.png"
  bio    : "Data Scientist"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ssulaihasubi@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sulaihasubi/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sulaihasubi"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@ssulaihasubi"
    - label: "Kaggle"
      icon: "fab fa-fw fa-kaggle"
      url: "https://www.kaggle.com/sulaihasubi" 

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sulaihasubi/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sulaihasubi"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@ssulaihasubi"
    - label: "Kaggle"
      icon: "fab fa-fw fa-kaggle"
      url: "https://www.kaggle.com/sulaihasubi" 
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
